source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.3'
gem 'mysql2'

# Server
gem 'unicorn', '~> 5.3.0'

# Worker
gem 'delayed_job_active_record', '~> 4.1.2'
gem 'daemons', '~> 1.2.4'

# MemCache Gem
gem 'dalli', '~> 2.7.6'

# SubModels
gem 'cocoon', '~> 1.2.10'

# CSS/JS
gem 'sass-rails', '~> 5.0.6'
gem 'uglifier', '~> 3.2.0'
gem 'coffee-rails', '~> 4.2.2'
gem 'bootstrap-sass', '~> 3.3.7'
gem "bootstrap-switch-rails"
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'momentjs-rails', '~> 2.17.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.47'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'jc-validates_timeliness'
gem 'jquery-ui-rails'

gem 'chartkick'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7.0'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring', group: :development

# Print out variables for debugging
gem 'awesome_print'

group :test do
  gem 'minitest'
end

group :development do
  gem 'pry-nav'
  gem 'pry-stack_explorer'
end

# Encryption
gem 'devise', git: 'https://github.com/gogovan/devise.git', branch: 'rails-5.1'
gem 'erubis'
gem 'bcrypt', :require => 'bcrypt'
gem 'symmetric-encryption', '~> 3.9.1'

gem 'aws-sdk', '~> 2.10.21'
gem 'colorize'

gem 'rest-client'

gem 'factory_girl', '~> 4.8.0'

gem 'tzinfo-data'