version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "88:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  db:
    image: mysql:5.7.7
    volumes_from:
      - dbdata
    environment:
      MYSQL_ROOT_PASSWORD: "lts_password"
    ports:
      - "3306:3306"
  dbdata:
    image: mysql:5.7.7
    command: /bin/echo mysql Data container
  redis:
    image: redis
  cache:
    image: memcached
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../code/:/loadtestserver
    command: bundle exec unicorn -E development -c config/unicorn_docker.rb
    environment:
      LTS_DATABASE_HOST_DEV: "db"
      LTS_DATABASE_USER_DEV: "root"
      LTS_DATABASE_PASS_DEV: "lts_password"

      LTS_DATABASE_HOST_PROD: "db"
      LTS_DATABASE_USER_PROD: "root"
      LTS_DATABASE_PASS_PROD: "lts_password"

      LTS_SECRET_KEY_BASE: "5k4jzPRICwBFzf6h7QFxMegHNf1GIIaPbyqqvfLrLCSPmayfs6gjTK5bhCJD0Cu5UO3UIPWAO0DIllynjVvkkp3rcjgeVt4Pff1x"
      LTS_DEVISE_SECRET_KEY: "5k4jzPRICwBFzf6h7QFxMegHNf1GIIaPbyqqvfLrLCSPmayfs6gjTK5bhCJD0Cu5UO3UIPWAO0DIllynjVvkkp3rcjgeVt4Pff1x"
      LTS_ENCRYPTION_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCFSgjjXgXF7kxz0TYZEdvLrBkbP5U2KtD2MJp0+E9rtHdKNfZa\nMOwiu/nqaW4kFjFF/nI/sc1uahPfZueEdcu3+hs+Eu78cML69DA4C79raxBaGNUE\nWFWwqd43lU10tKiY2lLMCbx5MoFRLMAuyYnYLaTUMUiWN2O4C5xrp2TefwIDAQAB\nAoGAR2YLMNBSw14NMhUlp3Q7ivSbVk9O/H8fBGGwu2uwD3/STrxtRI7kTw7mprzn\nNQl2R4ovZRM3eif0kT0sU3ZOM27mAoh6ThwABDqtrUN0mhuOEUzKXAS4pXaxf2ku\n73BfqKG0W1yXrmdpRaJCDAcsNq/uIQkuNAli+1TD0vhVO8ECQQDCzmxyWNVGoirQ\nNiYK+Y9ARGBnr9dvdtOgtXISN4vB/h1iiYYGUIA5r6KqKjwSGhgxSisU0xYP9ur1\nB6rVyZyRAkEAryijnCWSW5GBSs0bZtXkN3RrQSO2CfUtG+SpX6/MzhhH6qzISfV7\nSko20cCPyBrPuKW76l37TsQryVzh3aqSDwJBAIe8DRQfkXuFww8Qq7E58fZ1rjaQ\n7ytbQFnaE4Fd8qNYzGC8MgZ0UOPg3RZ0FycFx5WQeDQqYFT/VvckQIR11gECQELm\n+tcBYs2m3gN8JCM7P1gPF4hh434aL4if5jGuLEPr8kwogrf9E4JkpluneUOtOfoF\nE6mJDBwhwbe/ymWoaPECQEd5RJUR+t/GFKPzfTSwkpyE5sooFHIfhuIk7LbGBe7r\nyhPAc8q+jvMQc8Ibo5uJk+aEAStFrJtlODj9Bfr5UGc=\n-----END RSA PRIVATE KEY-----\n"

      RAILS_ENV: "development"
    links:
      - db
      - redis
      - cache
  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../code/:/loadtestserver
    command: bundle exec rake jobs:work
    environment:
      LTS_DATABASE_HOST_DEV: "db"
      LTS_DATABASE_USER_DEV: "root"
      LTS_DATABASE_PASS_DEV: "lts_password"

      LTS_DATABASE_HOST_PROD: "db"
      LTS_DATABASE_USER_PROD: "root"
      LTS_DATABASE_PASS_PROD: "lts_password"

      LTS_SECRET_KEY_BASE: "5k4jzPRICwBFzf6h7QFxMegHNf1GIIaPbyqqvfLrLCSPmayfs6gjTK5bhCJD0Cu5UO3UIPWAO0DIllynjVvkkp3rcjgeVt4Pff1x"
      LTS_DEVISE_SECRET_KEY: "5k4jzPRICwBFzf6h7QFxMegHNf1GIIaPbyqqvfLrLCSPmayfs6gjTK5bhCJD0Cu5UO3UIPWAO0DIllynjVvkkp3rcjgeVt4Pff1x"
      LTS_ENCRYPTION_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCFSgjjXgXF7kxz0TYZEdvLrBkbP5U2KtD2MJp0+E9rtHdKNfZa\nMOwiu/nqaW4kFjFF/nI/sc1uahPfZueEdcu3+hs+Eu78cML69DA4C79raxBaGNUE\nWFWwqd43lU10tKiY2lLMCbx5MoFRLMAuyYnYLaTUMUiWN2O4C5xrp2TefwIDAQAB\nAoGAR2YLMNBSw14NMhUlp3Q7ivSbVk9O/H8fBGGwu2uwD3/STrxtRI7kTw7mprzn\nNQl2R4ovZRM3eif0kT0sU3ZOM27mAoh6ThwABDqtrUN0mhuOEUzKXAS4pXaxf2ku\n73BfqKG0W1yXrmdpRaJCDAcsNq/uIQkuNAli+1TD0vhVO8ECQQDCzmxyWNVGoirQ\nNiYK+Y9ARGBnr9dvdtOgtXISN4vB/h1iiYYGUIA5r6KqKjwSGhgxSisU0xYP9ur1\nB6rVyZyRAkEAryijnCWSW5GBSs0bZtXkN3RrQSO2CfUtG+SpX6/MzhhH6qzISfV7\nSko20cCPyBrPuKW76l37TsQryVzh3aqSDwJBAIe8DRQfkXuFww8Qq7E58fZ1rjaQ\n7ytbQFnaE4Fd8qNYzGC8MgZ0UOPg3RZ0FycFx5WQeDQqYFT/VvckQIR11gECQELm\n+tcBYs2m3gN8JCM7P1gPF4hh434aL4if5jGuLEPr8kwogrf9E4JkpluneUOtOfoF\nE6mJDBwhwbe/ymWoaPECQEd5RJUR+t/GFKPzfTSwkpyE5sooFHIfhuIk7LbGBe7r\nyhPAc8q+jvMQc8Ibo5uJk+aEAStFrJtlODj9Bfr5UGc=\n-----END RSA PRIVATE KEY-----\n"

      RAILS_ENV: "development"
    links:
      - db
      - redis
      - cache
