version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "88:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../code/:/rails
    command: "bundle exec unicorn -E development -c config/unicorn_docker.rb"
    environment:
      LTS_DATABASE_HOST_DEV: 'db'
      LTS_DATABASE_USER_DEV: 'root'
      LTS_DATABASE_PASS_DEV: 'pass'

      LTS_DATABASE_HOST_PROD: 'db'
      LTS_DATABASE_USER_PROD: 'root'
      LTS_DATABASE_PASS_PROD: 'pass'

      LTS_SECRET_KEY_BASE: "5k4jzPRICwBFzf6h7QFxMegHNf1GIIaPbyqqvfLrLCSPmayfs6gjTK5bhCJD0Cu5UO3UIPWAO0DIllynjVvkkp3rcjgeVt4Pff1x"
      LTS_ENCRYPTION_KEY: "lrpGN6tV0yCGzA9kRyEPm1yqU5ZyZH6aWKCThXY1eXOWnRY1LEXwEleaOkHRRbjZ7g8TN3JHbetxsPNbLpfvSkqPVj0yqgPsbMTp"
      LTS_DEVISE_SECRET_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQCFSgjjXgXF7kxz0TYZEdvLrBkbP5U2KtD2MJp0+E9rtHdKNfZa
MOwiu/nqaW4kFjFF/nI/sc1uahPfZueEdcu3+hs+Eu78cML69DA4C79raxBaGNUE
WFWwqd43lU10tKiY2lLMCbx5MoFRLMAuyYnYLaTUMUiWN2O4C5xrp2TefwIDAQAB
AoGAR2YLMNBSw14NMhUlp3Q7ivSbVk9O/H8fBGGwu2uwD3/STrxtRI7kTw7mprzn
NQl2R4ovZRM3eif0kT0sU3ZOM27mAoh6ThwABDqtrUN0mhuOEUzKXAS4pXaxf2ku
73BfqKG0W1yXrmdpRaJCDAcsNq/uIQkuNAli+1TD0vhVO8ECQQDCzmxyWNVGoirQ
NiYK+Y9ARGBnr9dvdtOgtXISN4vB/h1iiYYGUIA5r6KqKjwSGhgxSisU0xYP9ur1
B6rVyZyRAkEAryijnCWSW5GBSs0bZtXkN3RrQSO2CfUtG+SpX6/MzhhH6qzISfV7
Sko20cCPyBrPuKW76l37TsQryVzh3aqSDwJBAIe8DRQfkXuFww8Qq7E58fZ1rjaQ
7ytbQFnaE4Fd8qNYzGC8MgZ0UOPg3RZ0FycFx5WQeDQqYFT/VvckQIR11gECQELm
+tcBYs2m3gN8JCM7P1gPF4hh434aL4if5jGuLEPr8kwogrf9E4JkpluneUOtOfoF
E6mJDBwhwbe/ymWoaPECQEd5RJUR+t/GFKPzfTSwkpyE5sooFHIfhuIk7LbGBe7r
yhPAc8q+jvMQc8Ibo5uJk+aEAStFrJtlODj9Bfr5UGc=
-----END RSA PRIVATE KEY-----
"
      RAILS_ENV: "development"
    links:
      - db
      - redis
      - cache
  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../code/:/rails
    command: "bundle exec rake jobs:work"
    environment:
      LTS_DATABASE_HOST_DEV: 'db'
      LTS_DATABASE_USER_DEV: 'root'
      LTS_DATABASE_PASS_DEV: 'pass'

      LTS_DATABASE_HOST_PROD: 'db'
      LTS_DATABASE_USER_PROD: 'root'
      LTS_DATABASE_PASS_PROD: 'pass'

      LTS_SECRET_KEY_BASE: "5k4jzPRICwBFzf6h7QFxMegHNf1GIIaPbyqqvfLrLCSPmayfs6gjTK5bhCJD0Cu5UO3UIPWAO0DIllynjVvkkp3rcjgeVt4Pff1x"
      LTS_ENCRYPTION_KEY: "lrpGN6tV0yCGzA9kRyEPm1yqU5ZyZH6aWKCThXY1eXOWnRY1LEXwEleaOkHRRbjZ7g8TN3JHbetxsPNbLpfvSkqPVj0yqgPsbMTp"
      LTS_DEVISE_SECRET_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQCFSgjjXgXF7kxz0TYZEdvLrBkbP5U2KtD2MJp0+E9rtHdKNfZa
MOwiu/nqaW4kFjFF/nI/sc1uahPfZueEdcu3+hs+Eu78cML69DA4C79raxBaGNUE
WFWwqd43lU10tKiY2lLMCbx5MoFRLMAuyYnYLaTUMUiWN2O4C5xrp2TefwIDAQAB
AoGAR2YLMNBSw14NMhUlp3Q7ivSbVk9O/H8fBGGwu2uwD3/STrxtRI7kTw7mprzn
NQl2R4ovZRM3eif0kT0sU3ZOM27mAoh6ThwABDqtrUN0mhuOEUzKXAS4pXaxf2ku
73BfqKG0W1yXrmdpRaJCDAcsNq/uIQkuNAli+1TD0vhVO8ECQQDCzmxyWNVGoirQ
NiYK+Y9ARGBnr9dvdtOgtXISN4vB/h1iiYYGUIA5r6KqKjwSGhgxSisU0xYP9ur1
B6rVyZyRAkEAryijnCWSW5GBSs0bZtXkN3RrQSO2CfUtG+SpX6/MzhhH6qzISfV7
Sko20cCPyBrPuKW76l37TsQryVzh3aqSDwJBAIe8DRQfkXuFww8Qq7E58fZ1rjaQ
7ytbQFnaE4Fd8qNYzGC8MgZ0UOPg3RZ0FycFx5WQeDQqYFT/VvckQIR11gECQELm
+tcBYs2m3gN8JCM7P1gPF4hh434aL4if5jGuLEPr8kwogrf9E4JkpluneUOtOfoF
E6mJDBwhwbe/ymWoaPECQEd5RJUR+t/GFKPzfTSwkpyE5sooFHIfhuIk7LbGBe7r
yhPAc8q+jvMQc8Ibo5uJk+aEAStFrJtlODj9Bfr5UGc=
-----END RSA PRIVATE KEY-----
"
      RAILS_ENV: "development"
    links:
      - db
      - redis
      - cache
  db:
    image: mysql:5.7.7
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "3306:3306"
  redis:
    image: redis
  cache:
    image: memcached
